INSERT INTO public.questions (id, text, category, likescount, dislikescount) VALUES (1, 'Кто первым доказал периодичность появления комет?', 'Астрономия', 0, 0);
INSERT INTO public.questions (id, text, category, likescount, dislikescount) VALUES (2, 'Какая поэма есть у В.В.Маяковского?', 'Литература', 0, 0);
INSERT INTO public.questions (id, text, category, likescount, dislikescount) VALUES (4, 'Сонет - поэтический жанр, в котором регламентируется количество строк. Сколько их должно быть?', 'Литература', 0, 0);
INSERT INTO public.questions (id, text, category, likescount, dislikescount) VALUES (3, 'В какой стране правило около двух десятков королей с одинаковыми именами?', 'История', 0, 0);
INSERT INTO public.questions (id, text, category, likescount, dislikescount) VALUES (5, 'Сколько глаз у пчелы?', 'Флора и фауна', 0, 0);
INSERT INTO public.questions (id, text, category, likescount, dislikescount) VALUES (6, 'Как звали  французского генерала, именем которого назван определенный фасон брюк?  ', 'История', 0, 0);
INSERT INTO public.questions (id, text, category, likescount, dislikescount) VALUES (7, 'Столица Сан-Томе и Принсипи?', 'География', 0, 0);

INSERT INTO public.answers (id, text, questionid, isright) VALUES (8, 'Галлей', 1, true);
INSERT INTO public.answers (id, text, questionid, isright) VALUES (12, 'Флейта-позвоночник', 2, true);
INSERT INTO public.answers (id, text, questionid, isright) VALUES (16, '14', 4, true);
INSERT INTO public.answers (id, text, questionid, isright) VALUES (18, 'Франция', 3, true);
INSERT INTO public.answers (id, text, questionid, isright) VALUES (25, '5', 5, true);
INSERT INTO public.answers (id, text, questionid, isright) VALUES (27, 'Галифе', 6, true);
INSERT INTO public.answers (id, text, questionid, isright) VALUES (31, 'Сан-Томе', 7, true);
INSERT INTO public.answers (id, text, questionid, isright) VALUES (15, '12', 4, false);
INSERT INTO public.answers (id, text, questionid, isright) VALUES (14, '10', 4, false);
INSERT INTO public.answers (id, text, questionid, isright) VALUES (9, 'Свирель-губы', 2, false);
INSERT INTO public.answers (id, text, questionid, isright) VALUES (11, 'Скрипка-ладони', 2, false);
INSERT INTO public.answers (id, text, questionid, isright) VALUES (10, 'Коперник', 1, false);
INSERT INTO public.answers (id, text, questionid, isright) VALUES (7, 'Кеплер', 1, false);
INSERT INTO public.answers (id, text, questionid, isright) VALUES (6, 'Галилей', 1, false);
INSERT INTO public.answers (id, text, questionid, isright) VALUES (33, 'Принсипи', 7, false);
INSERT INTO public.answers (id, text, questionid, isright) VALUES (29, 'Клеш', 6, false);
INSERT INTO public.answers (id, text, questionid, isright) VALUES (28, 'Джинсы', 6, false);
INSERT INTO public.answers (id, text, questionid, isright) VALUES (32, 'Пици', 7, false);
INSERT INTO public.answers (id, text, questionid, isright) VALUES (30, 'Валли', 7, false);
INSERT INTO public.answers (id, text, questionid, isright) VALUES (24, '4', 5, false);
INSERT INTO public.answers (id, text, questionid, isright) VALUES (26, 'Шаровары', 6, false);
INSERT INTO public.answers (id, text, questionid, isright) VALUES (21, 'Великобритания', 3, false);
INSERT INTO public.answers (id, text, questionid, isright) VALUES (20, 'Австрия', 3, false);
INSERT INTO public.answers (id, text, questionid, isright) VALUES (23, '3', 5, false);
INSERT INTO public.answers (id, text, questionid, isright) VALUES (22, '2', 5, false);
INSERT INTO public.answers (id, text, questionid, isright) VALUES (17, '16', 4, false);
INSERT INTO public.answers (id, text, questionid, isright) VALUES (19, 'Германия', 3, false);
INSERT INTO public.answers (id, text, questionid, isright) VALUES (13, 'Барабан-нервы', 2, false);